### ISSUE TITLE
Check form redirect on failed invoice creation not working

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/commerce_btcpay#10]
On checkout payment form if the invoice creation seems to fail. 

```
Notice: Undefined property: Drupal\commerce_btcpay\PluginForm\BtcPayRedirectForm::$checkoutFlow in Drupal\commerce_btcpay\PluginForm\BtcPayRedirectForm->redirectToPreviousStep() (line 67 of /var/www/html/drupal8/web/modules/contrib/commerce_btcpay/src/PluginForm/BtcPayRedirectForm.php) #0 /var/www/html/drupal8/web/core/includes/bootstrap.inc(582): _drupal_error_handler_real(8, 'Undefined prope...', '/var/www/html/d...', 67, Array) #1 
```

```
Error: Call to a member function getPane() on null in Drupal\commerce_btcpay\PluginForm\BtcPayRedirectForm->redirectToPreviousStep() (line 67 of /var/www/html/drupal8/web/modules/contrib/commerce_btcpay/src/PluginForm/BtcPayRedirectForm.php) #0 /var/www/html/drupal8/web/modules/contrib/commerce_btcpay/src/PluginForm/BtcPayRedirectForm.php(41): Drupal\commerce_btcpay\PluginForm\BtcPayRedirectForm->redirectToPreviousStep() #1 /var/www/html/drupal8/web/modules/contrib/commerce/modules/payment/src/Element/PaymentGatewayForm.php(93): Drupal\commerce_btcpay\PluginForm\BtcPayRedirectForm->buildConfigurationForm(Array, Object(Drupal\Core\Form\FormState)) #2 [internal function]: Drupal\commerce_payment\Element\PaymentGatewayForm::processForm(Array, Object(Drupal\Core\Form\FormState), Array) #3 /var/www/html/drupal8/web/core/lib/Drupal/Core/Form/FormBuilder.php(997): call_user_func_array(Array, Array) #4 /var/www/html/drupal8/web/core/lib/Drupal/Core/Form/FormBuilder.php(1060): Drupal\Core\Form\FormBuilder->doBuildForm('commerce_checko...', Array, Object(Drupal\Core\Form\FormState)) #5 
```

**Comment by ndeet** [comment]
Closing as it was likely fixed with #32.
